version: '2.1'

services:
  cc-a3-frontend:
    image: cc-a3-frontend
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js